# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialoguebox.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog


class Ui_Dialog(QDialog):
    def __init__(self, title, message, parent):
        super().__init__(parent=parent)
        self.title = title
        self.message = message
        self.setupUi(self)

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(350, 167)
        Dialog.setStyleSheet("background:rgb(22, 33, 62)")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setStyleSheet("color:white;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.ok_btn = QtWidgets.QPushButton(Dialog)
        self.ok_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ok_btn.setStyleSheet("QPushButton { \n"
                                  "    background:rgb(160, 132, 202); \n"
                                  "    color:white;\n"
                                  "    border: 2px solid rgb(164, 136, 207);\n"
                                  "      border-radius: 5px;\n"
                                  "    height:20px;\n"
                                  "    width:50px;\n"
                                  " }\n"
                                  "QPushButton:hover { \n"
                                  "    background:rgb(164, 136, 207);\n"
                                  "border: 2px solid rgb(160, 132, 202);\n"
                                  "      border-radius: 5px;\n"
                                  "}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ok_btn.setIcon(icon)
        self.ok_btn.setObjectName("ok_btn")
        self.verticalLayout.addWidget(self.ok_btn)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.ok_btn.clicked.connect(lambda: self.accept())

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", self.title))
        self.label.setText(_translate("Dialog", self.message))
        self.ok_btn.setText(_translate("Dialog", "OK"))
