# -*- coding: utf-8 -*-
import json

# Form implementation generated from reading ui file 'showBlocked.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog


class Ui_Dialog(QDialog):
    def __init__(self, parent):
        super().__init__(parent)
        self.setupUi(self)

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(560, 436)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/facebook (3).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("background:rgb(22, 33, 62)")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.userTabel_tbl = QtWidgets.QTableWidget(Dialog)
        self.userTabel_tbl.setStyleSheet("QTableWidget{\n"
                                         "background:rgb(255, 255, 255);\n"
                                         "border: 2px solid rgb(160, 132, 202);\n"
                                         "border-radius:5px;\n"
                                         "}")
        self.userTabel_tbl.setEditTriggers(QtWidgets.QAbstractItemView.AllEditTriggers)
        self.userTabel_tbl.setAlternatingRowColors(True)
        self.userTabel_tbl.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.userTabel_tbl.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.userTabel_tbl.setColumnCount(2)
        self.userTabel_tbl.setObjectName("userTabel_tbl")
        self.userTabel_tbl.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.userTabel_tbl.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.userTabel_tbl.setHorizontalHeaderItem(1, item)
        self.userTabel_tbl.horizontalHeader().setCascadingSectionResizes(True)
        self.userTabel_tbl.horizontalHeader().setSortIndicatorShown(True)
        self.userTabel_tbl.horizontalHeader().setStretchLastSection(True)
        self.userTabel_tbl.verticalHeader().setCascadingSectionResizes(True)
        self.userTabel_tbl.verticalHeader().setSortIndicatorShown(True)
        self.userTabel_tbl.verticalHeader().setVisible(False)
        self.userTabel_tbl.verticalHeader().setStretchLastSection(False)
        header = self.userTabel_tbl.horizontalHeader()
        header.setSectionResizeMode(0, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(1, QtWidgets.QHeaderView.Stretch)
        self.verticalLayout.addWidget(self.userTabel_tbl)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.select_all_btn = QtWidgets.QPushButton(self.widget)
        self.select_all_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.select_all_btn.setStyleSheet("QPushButton { \n"
                                          "    background:rgb(160, 132, 202); \n"
                                          "    color:white;\n"
                                          "    border: 2px solid rgb(164, 136, 207);\n"
                                          "      border-radius: 5px;\n"
                                          "    height:20px;\n"
                                          "    width:50px;\n"
                                          " }\n"
                                          "QPushButton:hover { \n"
                                          "    background:rgb(164, 136, 207);\n"
                                          "border: 2px solid rgb(160, 132, 202);\n"
                                          "      border-radius: 5px;\n"
                                          "}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/selection.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.select_all_btn.setIcon(icon1)
        self.select_all_btn.setObjectName("select_all_btn")
        self.horizontalLayout.addWidget(self.select_all_btn)
        self.unselect_all_btn = QtWidgets.QPushButton(self.widget)
        self.unselect_all_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.unselect_all_btn.setStyleSheet("QPushButton { \n"
                                            "    background:rgb(160, 132, 202); \n"
                                            "    color:white;\n"
                                            "    border: 2px solid rgb(164, 136, 207);\n"
                                            "      border-radius: 5px;\n"
                                            "    height:20px;\n"
                                            "    width:50px;\n"
                                            " }\n"
                                            "QPushButton:hover { \n"
                                            "    background:rgb(164, 136, 207);\n"
                                            "border: 2px solid rgb(160, 132, 202);\n"
                                            "      border-radius: 5px;\n"
                                            "}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/eliminate.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.unselect_all_btn.setIcon(icon2)
        self.unselect_all_btn.setObjectName("unselect_all_btn")
        self.horizontalLayout.addWidget(self.unselect_all_btn)
        self.unblock_btn = QtWidgets.QPushButton(self.widget)
        self.unblock_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.unblock_btn.setStyleSheet("QPushButton { \n"
                                       "    background:rgb(160, 132, 202); \n"
                                       "    color:white;\n"
                                       "    border: 2px solid rgb(164, 136, 207);\n"
                                       "      border-radius: 5px;\n"
                                       "    height:20px;\n"
                                       "    width:50px;\n"
                                       " }\n"
                                       "QPushButton:hover { \n"
                                       "    background:rgb(164, 136, 207);\n"
                                       "border: 2px solid rgb(160, 132, 202);\n"
                                       "      border-radius: 5px;\n"
                                       "}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/unlock.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.unblock_btn.setIcon(icon3)
        self.unblock_btn.setObjectName("unblock_btn")
        self.horizontalLayout.addWidget(self.unblock_btn)
        self.save_btn = QtWidgets.QPushButton(self.widget)
        self.save_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.save_btn.setStyleSheet("QPushButton { \n"
                                    "    background:rgb(160, 132, 202); \n"
                                    "    color:white;\n"
                                    "    border: 2px solid rgb(164, 136, 207);\n"
                                    "      border-radius: 5px;\n"
                                    "    height:20px;\n"
                                    "    width:50px;\n"
                                    " }\n"
                                    "QPushButton:hover { \n"
                                    "    background:rgb(164, 136, 207);\n"
                                    "border: 2px solid rgb(160, 132, 202);\n"
                                    "      border-radius: 5px;\n"
                                    "}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/diskette.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_btn.setIcon(icon4)
        self.save_btn.setObjectName("save_btn")
        self.horizontalLayout.addWidget(self.save_btn)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.setup_buttons()
        self.load_data()

    def setup_buttons(self):
        self.select_all_btn.clicked.connect(self.select_all)
        self.unselect_all_btn.clicked.connect(self.unselect_all)
        self.unblock_btn.clicked.connect(self.unblock_selected_users)
        self.save_btn.clicked.connect(self.save)

    def unblock_selected_users(self):
        try:
            previous_data = open('users.json', 'r')
            data = dict(json.load(previous_data))
            for row in range(0, self.userTabel_tbl.rowCount()):
                selected = True if self.userTabel_tbl.item(row, 0).checkState() == 2 else False
                user = self.userTabel_tbl.item(row, 1).text()
                if selected and 'false' in data[user]:
                    posts = data[user]['false']
                    data[user] = {True: posts}
            with open('users.json', 'w') as file:
                file.write(json.dumps(data, indent=4))
            self.load_data()
        except FileNotFoundError:
            return

    def merge_data(self, new_data: dict) -> dict:
        try:
            previous_data = open('users.json', 'r')
            data = dict(json.load(previous_data))
            for d in new_data:
                new_data[d] = data[d]
            previous_data.close()
            return new_data
        except FileNotFoundError:
            return new_data

    def save(self):
        self.accept()

    def load_data(self):
        try:
            users = open('users.json', 'r')
            data = dict(json.load(users))
            row_index = self.userTabel_tbl.rowCount()
            for row in range(0, row_index):
                self.userTabel_tbl.removeRow(0)
            for key in data:
                for user_status in data[key]:
                    selected = user_status
                    if 'false' in selected:
                        row_index = self.userTabel_tbl.rowCount()
                        self.userTabel_tbl.insertRow(row_index)
                        check_box = QtWidgets.QTableWidgetItem()
                        check_box.setFlags(QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
                        check_box.setCheckState(QtCore.Qt.Unchecked)
                        self.userTabel_tbl.setItem(row_index, 0, check_box)
                        self.userTabel_tbl.setItem(row_index, 1, QtWidgets.QTableWidgetItem(key))
        except FileNotFoundError:
            pass

    def select_all(self):
        # self.userTabel_tbl.setCol
        for row in range(0, self.userTabel_tbl.rowCount()):
            col = self.userTabel_tbl.item(row, 0)
            col.setCheckState(QtCore.Qt.Checked)

    def unselect_all(self):
        # self.userTabel_tbl.setCol
        for row in range(0, self.userTabel_tbl.rowCount()):
            col = self.userTabel_tbl.item(row, 0)
            col.setCheckState(QtCore.Qt.Unchecked)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Show Blocked"))
        item = self.userTabel_tbl.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "#"))
        item = self.userTabel_tbl.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Link"))
        self.select_all_btn.setText(_translate("Dialog", "Select All"))
        self.unselect_all_btn.setText(_translate("Dialog", "Unselect All"))
        self.unblock_btn.setText(_translate("Dialog", "Unblock"))
        self.save_btn.setText(_translate("Dialog", "Save"))
        self.userTabel_tbl.setSortingEnabled(True)

